spring:
  application:
    name: mayarafurtado.paliar.br-springboot-backend
  config:
    import: optional:file:.env.properties[.properties]

  # JPA
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update # Pode ser "create" ou "validate" conforme necessário
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}

  doc:
    swagger-ui:
      enabled: true
      url: /v3/api-docs
    api-docs:
      path: /v3/api-docs
